name: Quiet Link Validator

on:
  schedule:
    - cron: '05 13 * * *' # 09:05 ET (13:05 UTC)
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (robust)
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          else
            echo "⚠️ No requirements.txt found, skipping install."
          fi

      - name: Run validator
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          LINKCHECK_DB_ID: ${{ secrets.LINKCHECK_DB_ID }}
          RADAR_DB_ID: ${{ secrets.RADAR_DB_ID }}
          PROJECT_TRACKER_DB_ID: ${{ secrets.PROJECT_TRACKER_DB_ID }}
          AFF_TAG: abinom55-20
        run: python scripts/quiet_validator.py


