name: CI — Validate required repository secrets

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  validate-secrets:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate required secrets exist
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          LINKCHECK_DB_ID: ${{ secrets.LINKCHECK_DB_ID }}
          RUN_LOG_DB_ID: ${{ secrets.RUN_LOG_DB_ID }}
        run: |
          set -euo pipefail
          missing=()
          [[ -z "${NOTION_TOKEN:-}" ]] && missing+=("NOTION_TOKEN")
          [[ -z "${LINKCHECK_DB_ID:-}" ]] && missing+=("LINKCHECK_DB_ID")
          [[ -z "${RUN_LOG_DB_ID:-}" ]] && missing+=("RUN_LOG_DB_ID")
          if [ ${#missing[@]} -gt 0 ]; then
            echo "❌ Missing required repository secrets: ${missing[*]}"
            exit 1
          fi
          echo "✅ All required repository secrets are present."

